### ISSUE TITLE
detailed information about the project

### ISSUE THREAD

**Issue by ShayanBits** [matthieuheitz/npy_viewer#1]
Hello Matthieu,

This is not an issue but a question.
1. I have some npy files containing high dimensional vectors. For example 1000. Is npy_viewer capable of visualizing such vectors as well? 
2. Is it possible to run the code on MacOS too?
3. Have you used t-SNE or PCA in this project?

Thank you

**Comment by matthieuheitz** [comment]
Hi !
1. For arrays of shapes (n,) as seems to be your case (n=1000), the only viewer that is relevant is NPYFileViewer, and it will just print the values in the terminal, as well as statistics about the values. If you want to *plot*the values in a graph, you can open your file using NPYLoadInShell, and then using matplotlib to plot it. But it's true that I could make a script for that... it's a good next feature to have.
2. Yes, since it's coded in Python, you can run it on Windows, Mac and Linux.
3. No I haven't used any dimensionality reduction algorithms like t-SNE or PCA in this project.

There might be a confusion between what you call "dimension" of the vector, which is its size, and what I call the "dimension" of an array, which is the number of axes it has, the [`ndim`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html) of numpy. So these scripts are mostly for numpy arrays where ndim=2 or 3.

**Comment by ShayanBits** [comment]
Thanks Matthieu for the answer. I will now close this issue.
